apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: random-meal-tls
  namespace: random-meal
spec:
  secretName: random-meal-tls
  dnsNames:
  - meal.haradore.co.uk
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      - meal.haradore.co.uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer